### PR TITLE
Change "Update" button to "Preview"

### PR DESCRIPTION
**Pull request by arnoesterhuizen**
...to help guide users to press the "Save & Publish" at the top of the
customizer.

If accepted, I can also change the help text to reflect the renaming of the button.

### CODE REVIEW

**Comment by westonruter** [comment]
@arnoesterhuizen thanks for the PR. I think we actually had it say Preview before. However, a Preview button is actually misleading because it makes it seem like clicking it is optional. However, if you don't click the button then the setting will never be updated and their changes will not be saved. So I think something more forceful is needed.

**Comment by arnoesterhuizen** [comment]
Maybe using "Apply"? I guess this would need more user testing. 

Feel free to delete the pull request if this isn't viable right now.

**Comment by westonruter** [comment]
@shaunandrews what do you think? Is "Apply" better than "Update"?

**Comment by shaunandrews** [comment]
I like Apply.

**Comment by westonruter** [comment]
@arnoesterhuizen you can go ahead and change it to using "Apply". How would you change the help text?

**Comment by arnoesterhuizen** [comment]
Just changing the text in the readme files to refer to the "Apply" button. The screenshots I won't be able to help with necessarily, but I can try.

**Comment by westonruter** [comment]
Thanks! Merged into `develop`.

**Pull request closed without merging**
